### ISSUE TITLE
No Module named billing_entities

### ISSUE THREAD

**Issue by cosmo83** [silverapp/silver#534]
Iam having an issue running silver in my django application.

I have added silver in my INSTALLED_APPS, and get the following traceback when iam running migrate. Need to understand what iam missing .

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib64/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib64/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/site-packages/silver/models/__init__.py", line 15, in <module>
    from billing_entities import Customer, Provider
ImportError: No module named 'billing_entities'

**Comment by bogdanpetrea** [comment]
Same as https://github.com/silverapp/silver/issues/545.
